---
output:
  pdf_document: default
  html_document: default
---
#1.There is a built-in vector
LETTERS
letters
#a. You need to produce a vector that contains the first 11 letter.
LETTERS[1:11]
letters[1:11]
#b. Produce a vector that contains the odd numbered letters.
LETTERS[x=seq(1,26,by=2)]
letters[x=seq(1,26,by=2)]
#c.Produce a vector that contains the vowels
vowels <- LETTERS[c(1,5,9,15,21)]
vowels

#d. Produce a vector that contains the last 5 lowercase letters.
letters
ending <- letters[c(22:26)]
ending

#e. Produce a vector that contains letters between 15 to 24 letters in lowercase.
fifteen24 <- letters[c(15:24)]
fifteen24

#2 Create a vector(not a dataframe).
#a.What is the R code and its result for creating a character vector
seeT <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
seeT

#b. The average temperatures in Celcius
temperature <- c(42, 39, 34, 34, 30, 27)
temperature

#c. Create a dataframe to combine the city and the temp by using ‘data.frame().
seeTtemperature <- data.frame(seeT,temperature)
seeTtemperature 

#d. Associate the dataframe you have created
names(seeTtemperature) <- c("City", "Temperature")
seeTtemperature

#e.Print the structure by using str() function.

str(seeTtemperature)
# the code displayed the structure of the seeTtemperature object
# it displayed the contents of the data frame
# it displayed the summary of the data frame

#f.From the answer in d, what is the content of row 3 and row 4
rows <- seeTtemperature [3:4,]

#g.From the answer in d, display the city with highest temperature and the city with the lowest temperature.
highesttemp <- seeTtemperature[which.max(seeTtemperature$Temperature),]
highesttemp
lowesttemp <- seeTtemperature[which.min(seeTtemperature$Temperature),]
lowesttemp

# USING MATRICES
# 2a. What will be the R code for the #2 question and its result?
MATRIX <- matrix(c(1:8,11:14), nrow = 3, ncol = 4)
MATRIX

#2b. Multiply the matrix by two. What is its R code and its result?
mulMATRIX <- MATRIX * 2
mulMATRIX

#2c. What is the content of row 2? What is its R code?
row2 <- mulMATRIX [2,]
row2

#2d. What will be the R code if you want to display the column 3 and column 4 in row 1 and row 2?
twoColmrows <- mulMATRIX[c(1,2),c(3,4)]
twoColmrows

#2e. What is the R code is you want to display only the columns in 2 and 3, row 3?
twoColm1row <- mulMATRIX[3,c(2,3)]
twoColm1row

#2f. What is the R code is you want to display only the columns 4?

fourColm <- mulMATRIX[,4]
fourColm

#2g. Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro for the matrix that was created in b.

dimnames(mulMATRIX) <- list(c("isa", "dalawa", "tatlo"), c("uno", "dos", "tres", "quatro"))

mulMATRIX

#2h. From the original matrix you have created in a, reshape the matrix by assigning a new dimension with dim().
MATRIX
dim(MATRIX) <- c(6,2)
MATRIX


# ARRAYS
#3a. Create an array for the above numeric values. 

Values <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
RepValues <- rep(Values, each = 2)

ARRA <- array(RepValues, dim = c(2,4,3))
ARRA

#3b. How many dimensions do your array have? 
#the array has three dimensions

#3c. Name the rows as lowercase letters and columns as uppercase letters starting from the A.
dimnames(ARRA) <- list( letters[1:2], # row names LETTERS[1:4], # col names c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array") # dimnames )


